# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Airbnb' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


    post_install do |installer|
        installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
                    config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
              end
    end
    end


  # Pods for Airbnb
  pod 'SwiftLint'
  pod 'SnapKit', '~> 5.6.0'
  pod 'FSCalendar'
  pod 'GoogleMaps', '7.1.0'
  pod 'GooglePlaces', '7.1.0'
end
